wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240112_025141-8n2v72ts
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run earnest-shadow-79
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/PPO%2BPPOL
wandb: üöÄ View run at https://wandb.ai/ecrl/PPO%2BPPOL/runs/8n2v72ts
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 141, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 98, in train
    env = DummyVecEnv(envs)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 91, in _init
    env = FlattenObservation(load_environment(env_config, env_logger_path=args.env_logger_path))
TypeError: load_environment() got an unexpected keyword argument 'env_logger_path'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: wandb version 0.16.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240111_185141-4iscijyh
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run silver-frost-80
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/PPO%2BPPOL
wandb: üöÄ View run at https://wandb.ai/ecrl/PPO%2BPPOL/runs/4iscijyh
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 141, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 98, in train
    env = DummyVecEnv(envs)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 91, in _init
    env = FlattenObservation(load_environment(env_config, env_logger_path=args.env_logger_path))
TypeError: load_environment() got an unexpected keyword argument 'env_logger_path'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: wandb version 0.16.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240111_185141-g7hw5hw1
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run legendary-voice-81
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/PPO%2BPPOL
wandb: üöÄ View run at https://wandb.ai/ecrl/PPO%2BPPOL/runs/g7hw5hw1
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 141, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 98, in train
    env = DummyVecEnv(envs)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 91, in _init
    env = FlattenObservation(load_environment(env_config, env_logger_path=args.env_logger_path))
TypeError: load_environment() got an unexpected keyword argument 'env_logger_path'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: üöÄ View run earnest-shadow-79 at: https://wandb.ai/ecrl/PPO%2BPPOL/runs/8n2v72ts
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240112_025141-8n2v72ts/logs
wandb: üöÄ View run silver-frost-80 at: https://wandb.ai/ecrl/PPO%2BPPOL/runs/4iscijyh
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240111_185141-4iscijyh/logs
wandb: üöÄ View run legendary-voice-81 at: https://wandb.ai/ecrl/PPO%2BPPOL/runs/g7hw5hw1
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240111_185141-g7hw5hw1/logs
srun: error: airl.ist.berkeley.edu: task 0: Exited with exit code 1
srun: error: dqn.ist.berkeley.edu: task 0: Exited with exit code 1
srun: error: ddpg.ist.berkeley.edu: task 0: Exited with exit code 1
srun: Job 116061 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=116061.3
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240112_025341-lt3hkn4r
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run silver-waterfall-82
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/PPO%2BPPOL
wandb: üöÄ View run at https://wandb.ai/ecrl/PPO%2BPPOL/runs/lt3hkn4r
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 141, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 98, in train
    env = DummyVecEnv(envs)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 91, in _init
    env = FlattenObservation(load_environment(env_config, env_logger_path=args.env_logger_path))
TypeError: load_environment() got an unexpected keyword argument 'env_logger_path'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
srun: Job 116061 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=116061.4
srun: Job 116061 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=116061.5
wandb: üöÄ View run silver-waterfall-82 at: https://wandb.ai/ecrl/PPO%2BPPOL/runs/lt3hkn4r
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240112_025341-lt3hkn4r/logs
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
srun: Job 116061 step creation temporarily disabled, retrying (Requested nodes are busy)
wandb: wandb version 0.16.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240111_185346-18mwfqmk
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run firm-dawn-83
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/PPO%2BPPOL
wandb: üöÄ View run at https://wandb.ai/ecrl/PPO%2BPPOL/runs/18mwfqmk
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 141, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 98, in train
    env = DummyVecEnv(envs)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 91, in _init
    env = FlattenObservation(load_environment(env_config, env_logger_path=args.env_logger_path))
TypeError: load_environment() got an unexpected keyword argument 'env_logger_path'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
srun: Job 116061 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: error: airl.ist.berkeley.edu: task 0: Exited with exit code 1
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240111_185349-ju1zvf7t
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run flowing-night-84
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/PPO%2BPPOL
wandb: üöÄ View run at https://wandb.ai/ecrl/PPO%2BPPOL/runs/ju1zvf7t
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 141, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 98, in train
    env = DummyVecEnv(envs)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 91, in _init
    env = FlattenObservation(load_environment(env_config, env_logger_path=args.env_logger_path))
TypeError: load_environment() got an unexpected keyword argument 'env_logger_path'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: üöÄ View run firm-dawn-83 at: https://wandb.ai/ecrl/PPO%2BPPOL/runs/18mwfqmk
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240111_185346-18mwfqmk/logs
srun: error: ddpg.ist.berkeley.edu: task 0: Exited with exit code 1
wandb: üöÄ View run flowing-night-84 at: https://wandb.ai/ecrl/PPO%2BPPOL/runs/ju1zvf7t
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240111_185349-ju1zvf7t/logs
srun: error: dqn.ist.berkeley.edu: task 0: Exited with exit code 1
srun: Job 116061 step creation still disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=116061.6
srun: Job 116061 step creation still disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=116061.7
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240112_025558-zr8kdijg
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run comic-river-85
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/PPO%2BPPOL
wandb: üöÄ View run at https://wandb.ai/ecrl/PPO%2BPPOL/runs/zr8kdijg
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 141, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 98, in train
    env = DummyVecEnv(envs)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 91, in _init
    env = FlattenObservation(load_environment(env_config, env_logger_path=args.env_logger_path))
TypeError: load_environment() got an unexpected keyword argument 'env_logger_path'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240111_185600-u8g5m8ft
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run fluent-lake-86
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/PPO%2BPPOL
wandb: üöÄ View run at https://wandb.ai/ecrl/PPO%2BPPOL/runs/u8g5m8ft
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 141, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 98, in train
    env = DummyVecEnv(envs)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 30, in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 91, in _init
    env = FlattenObservation(load_environment(env_config, env_logger_path=args.env_logger_path))
TypeError: load_environment() got an unexpected keyword argument 'env_logger_path'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: üöÄ View run comic-river-85 at: https://wandb.ai/ecrl/PPO%2BPPOL/runs/zr8kdijg
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240112_025558-zr8kdijg/logs
wandb: üöÄ View run fluent-lake-86 at: https://wandb.ai/ecrl/PPO%2BPPOL/runs/u8g5m8ft
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240111_185600-u8g5m8ft/logs
srun: error: ddpg.ist.berkeley.edu: task 0: Exited with exit code 1
srun: error: airl.ist.berkeley.edu: task 0: Exited with exit code 1
