wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20231230_003506-y2zdddnx
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run jumping-waterfall-50
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D100
wandb: üöÄ View run at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D100/runs/y2zdddnx
wandb: wandb version 0.16.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20231230_003506-9wt179g0
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run gallant-dream-50
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D100
wandb: üöÄ View run at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D100/runs/9wt179g0
wandb: wandb version 0.16.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20231230_083506-al7glb8y
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run usual-morning-52
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D100
wandb: üöÄ View run at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D100/runs/al7glb8y
wandb: wandb version 0.16.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20231230_003506-idwyitsk
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run zany-sunset-53
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D100
wandb: üöÄ View run at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D100/runs/idwyitsk
Using cpu device
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 126, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 103, in train
    agent.learn(total_timesteps=args.total_timesteps, callback=callback, reset_num_timesteps=False)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/ppol/ppol.py", line 429, in learn
    result = super().learn(
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 572, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 489, in collect_rollouts
    if not callback.on_step():
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/callbacks.py", line 111, in on_step
    return self._on_step()
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 30, in _on_step
    cost = self.locals['cost']
KeyError: 'cost'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
Using cpu device
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 126, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 103, in train
    agent.learn(total_timesteps=args.total_timesteps, callback=callback, reset_num_timesteps=False)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/ppol/ppol.py", line 429, in learn
    result = super().learn(
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 572, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 489, in collect_rollouts
    if not callback.on_step():
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/callbacks.py", line 111, in on_step
    return self._on_step()
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 30, in _on_step
    cost = self.locals['cost']
KeyError: 'cost'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
Using cpu device
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 126, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 103, in train
    agent.learn(total_timesteps=args.total_timesteps, callback=callback, reset_num_timesteps=False)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/ppol/ppol.py", line 429, in learn
    result = super().learn(
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 572, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 489, in collect_rollouts
    if not callback.on_step():
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/callbacks.py", line 111, in on_step
    return self._on_step()
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 30, in _on_step
    cost = self.locals['cost']
KeyError: 'cost'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
Using cpu device
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 126, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 103, in train
    agent.learn(total_timesteps=args.total_timesteps, callback=callback, reset_num_timesteps=False)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/ppol/ppol.py", line 429, in learn
    result = super().learn(
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 572, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 489, in collect_rollouts
    if not callback.on_step():
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/callbacks.py", line 111, in on_step
    return self._on_step()
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 30, in _on_step
    cost = self.locals['cost']
KeyError: 'cost'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: üöÄ View run gallant-dream-50 at: https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D100/runs/9wt179g0
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20231230_003506-9wt179g0/logs
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: üöÄ View run jumping-waterfall-50 at: https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D100/runs/y2zdddnx
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20231230_003506-y2zdddnx/logs
srun: error: ddpg.ist.berkeley.edu: task 0: Exited with exit code 1
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: üöÄ View run zany-sunset-53 at: https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D100/runs/idwyitsk
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20231230_003506-idwyitsk/logs
srun: error: gail.ist.berkeley.edu: task 0: Exited with exit code 1
srun: error: dqn.ist.berkeley.edu: task 0: Exited with exit code 1
wandb: üöÄ View run usual-morning-52 at: https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D100/runs/al7glb8y
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20231230_083506-al7glb8y/logs
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 259, in check_network_status
    self._loop_check_status(
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 215, in _loop_check_status
    local_handle = request()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 795, in deliver_network_status
    return self._deliver_network_status(status)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 601, in _deliver_network_status
    return self._deliver_record(record)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 560, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
    interface._publish(record)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
srun: error: airl.ist.berkeley.edu: task 0: Exited with exit code 1
