wandb: Starting wandb agent üïµÔ∏è
wandb: Starting wandb agent üïµÔ∏è
wandb: Starting wandb agent üïµÔ∏è
wandb: Starting wandb agent üïµÔ∏è
wandb: Starting wandb agent üïµÔ∏è
wandb: Starting wandb agent üïµÔ∏è
2023-08-19 07:38:20,558 - wandb.wandb_agent - INFO - Running runs: []
2023-08-19 00:38:20,556 - wandb.wandb_agent - INFO - Running runs: []
2023-08-19 00:38:20,591 - wandb.wandb_agent - INFO - Running runs: []
2023-08-19 07:38:20,604 - wandb.wandb_agent - INFO - Running runs: []
2023-08-19 00:38:20,686 - wandb.wandb_agent - INFO - Running runs: []
2023-08-19 00:38:20,685 - wandb.wandb_agent - INFO - Running runs: []
2023-08-19 07:38:20,864 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 07:38:20,864 - wandb.wandb_agent - INFO - Agent starting run with config:
	lr: 0.001
	normalize_obs: False
2023-08-19 07:38:20,866 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo.py --lr=0.001 --normalize_obs=False
2023-08-19 00:38:20,877 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 00:38:20,877 - wandb.wandb_agent - INFO - Agent starting run with config:
	actor_lr: 0.001
	critic_lr: 0.001
	normalize_obs: False
2023-08-19 00:38:20,879 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py --actor_lr=0.001 --critic_lr=0.001 --normalize_obs=False
2023-08-19 07:38:21,073 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 07:38:21,073 - wandb.wandb_agent - INFO - Agent starting run with config:
	actor_lr: 0.001
	critic_lr: 0.001
	normalize_obs: True
2023-08-19 07:38:21,074 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py --actor_lr=0.001 --critic_lr=0.001 --normalize_obs=True
2023-08-19 00:38:21,092 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 00:38:21,092 - wandb.wandb_agent - INFO - Agent starting run with config:
	lr: 0.001
	normalize_obs: False
2023-08-19 00:38:21,095 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo.py --lr=0.001 --normalize_obs=False
2023-08-19 00:38:21,336 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 00:38:21,336 - wandb.wandb_agent - INFO - Agent starting run with config:
	actor_lr: 0.0005
	critic_lr: 0.0005
	normalize_obs: True
2023-08-19 00:38:21,339 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py --actor_lr=0.0005 --critic_lr=0.0005 --normalize_obs=True
2023-08-19 00:38:21,362 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 00:38:21,362 - wandb.wandb_agent - INFO - Agent starting run with config:
	lr: 0.0005
	normalize_obs: True
2023-08-19 00:38:21,364 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo.py --lr=0.0005 --normalize_obs=True
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_073823-lfwvj76m
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run copper-sweep-1
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/eito20j2
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/lfwvj76m
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_003823-38tauc1v
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run light-sweep-3
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/eito20j2
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/38tauc1v
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_003823-xz417wl5
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run smart-sweep-1
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/fjyc7cnz
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/xz417wl5
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_003823-1m93nvty
wandb: Run `wandb offline` to turn off syncing.
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: Syncing run peachy-sweep-2
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/eito20j2
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/1m93nvty
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_073823-94x66f7q
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run leafy-sweep-2
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/fjyc7cnz
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/94x66f7q
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_003824-4icec36y
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run silvery-sweep-3
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/fjyc7cnz
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/4icec36y
usage: train_cpo.py [-h] [--task TASK] [--epoch EPOCH] [--target_kl TARGET_KL]
                    [--lr LR] [--step_per_epoch STEP_PER_EPOCH]
                    [--gamma GAMMA] [--cost_limit FLOAT [FLOAT ...]]
                    [--render RENDER] [--render_mode RENDER_MODE]
                    [--thread THREAD]
                    [--constraint_type CONSTRAINT_TYPE [CONSTRAINT_TYPE ...]]
                    [--speed_limit SPEED_LIMIT]
                    [--absolute_cost_speed ABSOLUTE_COST_SPEED]
train_cpo.py: error: unrecognized arguments: --normalize_obs=False
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
usage: train_cpo.py [-h] [--task TASK] [--epoch EPOCH] [--target_kl TARGET_KL]
                    [--lr LR] [--step_per_epoch STEP_PER_EPOCH]
                    [--gamma GAMMA] [--cost_limit FLOAT [FLOAT ...]]
                    [--render RENDER] [--render_mode RENDER_MODE]
                    [--thread THREAD]
                    [--constraint_type CONSTRAINT_TYPE [CONSTRAINT_TYPE ...]]
                    [--speed_limit SPEED_LIMIT]
                    [--absolute_cost_speed ABSOLUTE_COST_SPEED]
train_cpo.py: error: unrecognized arguments: --normalize_obs=True
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
usage: train_cpo.py [-h] [--task TASK] [--epoch EPOCH] [--target_kl TARGET_KL]
                    [--lr LR] [--step_per_epoch STEP_PER_EPOCH]
                    [--gamma GAMMA] [--cost_limit FLOAT [FLOAT ...]]
                    [--render RENDER] [--render_mode RENDER_MODE]
                    [--thread THREAD]
                    [--constraint_type CONSTRAINT_TYPE [CONSTRAINT_TYPE ...]]
                    [--speed_limit SPEED_LIMIT]
                    [--absolute_cost_speed ABSOLUTE_COST_SPEED]
train_cpo.py: error: unrecognized arguments: --normalize_obs=False
2023-08-19 07:38:25,875 - wandb.wandb_agent - INFO - Running runs: ['lfwvj76m']
2023-08-19 07:38:25,875 - wandb.wandb_agent - INFO - Cleaning up finished run: lfwvj76m
wandb: Waiting for W&B process to finish... (failed 2). Press Control-C to abort syncing.
2023-08-19 00:38:25,888 - wandb.wandb_agent - INFO - Running runs: ['xz417wl5']
2023-08-19 00:38:25,888 - wandb.wandb_agent - INFO - Cleaning up finished run: xz417wl5
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
2023-08-19 07:38:26,083 - wandb.wandb_agent - INFO - Running runs: ['94x66f7q']
2023-08-19 07:38:26,083 - wandb.wandb_agent - INFO - Cleaning up finished run: 94x66f7q
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
2023-08-19 00:38:26,104 - wandb.wandb_agent - INFO - Running runs: ['1m93nvty']
2023-08-19 00:38:26,348 - wandb.wandb_agent - INFO - Running runs: ['4icec36y']
2023-08-19 00:38:26,349 - wandb.wandb_agent - INFO - Cleaning up finished run: 4icec36y
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
2023-08-19 00:38:26,373 - wandb.wandb_agent - INFO - Running runs: ['38tauc1v']
2023-08-19 00:38:26,373 - wandb.wandb_agent - INFO - Cleaning up finished run: 38tauc1v
wandb: Waiting for W&B process to finish... (failed 2). Press Control-C to abort syncing.
wandb: - 0.027 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: üöÄ View run smart-sweep-1 at: https://wandb.ai/ecrl/fast-safe-rl/runs/xz417wl5
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_003823-xz417wl5/logs
wandb: - 0.027 MB of 0.031 MB uploaded (0.000 MB deduped)wandb: üöÄ View run leafy-sweep-2 at: https://wandb.ai/ecrl/fast-safe-rl/runs/94x66f7q
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_073823-94x66f7q/logs
wandb: - 0.027 MB of 0.027 MB uploaded (0.000 MB deduped)wandb: üöÄ View run silvery-sweep-3 at: https://wandb.ai/ecrl/fast-safe-rl/runs/4icec36y
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_003824-4icec36y/logs
wandb: - 0.027 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: \ 0.030 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: üöÄ View run copper-sweep-1 at: https://wandb.ai/ecrl/fast-safe-rl/runs/lfwvj76m
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_073823-lfwvj76m/logs
wandb: - 0.027 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: \ 0.030 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: üöÄ View run light-sweep-3 at: https://wandb.ai/ecrl/fast-safe-rl/runs/38tauc1v
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_003823-38tauc1v/logs
2023-08-19 07:38:30,140 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 07:38:30,140 - wandb.wandb_agent - INFO - Agent starting run with config:
	actor_lr: 0.0005
	critic_lr: 0.001
	normalize_obs: True
2023-08-19 07:38:30,142 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py --actor_lr=0.0005 --critic_lr=0.001 --normalize_obs=True
2023-08-19 07:38:30,342 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 07:38:30,342 - wandb.wandb_agent - INFO - Agent starting run with config:
	lr: 0.0005
	normalize_obs: False
2023-08-19 07:38:30,344 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo.py --lr=0.0005 --normalize_obs=False
2023-08-19 00:38:30,455 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 00:38:30,455 - wandb.wandb_agent - INFO - Agent starting run with config:
	actor_lr: 0.0005
	critic_lr: 0.001
	normalize_obs: False
2023-08-19 00:38:30,457 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py --actor_lr=0.0005 --critic_lr=0.001 --normalize_obs=False
2023-08-19 00:38:30,736 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 00:38:30,736 - wandb.wandb_agent - INFO - Agent starting run with config:
	actor_lr: 0.0005
	critic_lr: 0.0005
	normalize_obs: False
2023-08-19 00:38:30,738 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py --actor_lr=0.0005 --critic_lr=0.0005 --normalize_obs=False
2023-08-19 00:38:30,797 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 00:38:30,797 - wandb.wandb_agent - INFO - Agent starting run with config:
	lr: 0.001
	normalize_obs: True
2023-08-19 00:38:30,799 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo.py --lr=0.001 --normalize_obs=True
2023-08-19 00:38:31,170 - wandb.wandb_agent - INFO - Cleaning up finished run: 1m93nvty
wandb: Waiting for W&B process to finish... (failed 2). Press Control-C to abort syncing.
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: - 0.030 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: üöÄ View run peachy-sweep-2 at: https://wandb.ai/ecrl/fast-safe-rl/runs/1m93nvty
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_003823-1m93nvty/logs
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_073832-iq2wvhp5
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run fast-sweep-4
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/eito20j2
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/iq2wvhp5
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_073833-4jqpel8a
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run glad-sweep-4
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/fjyc7cnz
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/4jqpel8a
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_003833-9qe4e2cu
wandb: Run `wandb offline` to turn off syncing.
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: Syncing run daily-sweep-5
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/eito20j2
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/9qe4e2cu
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_003833-4tc58zz4
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run glamorous-sweep-5
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/fjyc7cnz
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/4tc58zz4
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_003833-55vlrblr
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run kind-sweep-6
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/fjyc7cnz
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/55vlrblr
usage: train_cpo.py [-h] [--task TASK] [--epoch EPOCH] [--target_kl TARGET_KL]
                    [--lr LR] [--step_per_epoch STEP_PER_EPOCH]
                    [--gamma GAMMA] [--cost_limit FLOAT [FLOAT ...]]
                    [--render RENDER] [--render_mode RENDER_MODE]
                    [--thread THREAD]
                    [--constraint_type CONSTRAINT_TYPE [CONSTRAINT_TYPE ...]]
                    [--speed_limit SPEED_LIMIT]
                    [--absolute_cost_speed ABSOLUTE_COST_SPEED]
train_cpo.py: error: unrecognized arguments: --normalize_obs=False
wandb: Waiting for W&B process to finish... (failed 2). Press Control-C to abort syncing.
usage: train_cpo.py [-h] [--task TASK] [--epoch EPOCH] [--target_kl TARGET_KL]
                    [--lr LR] [--step_per_epoch STEP_PER_EPOCH]
                    [--gamma GAMMA] [--cost_limit FLOAT [FLOAT ...]]
                    [--render RENDER] [--render_mode RENDER_MODE]
                    [--thread THREAD]
                    [--constraint_type CONSTRAINT_TYPE [CONSTRAINT_TYPE ...]]
                    [--speed_limit SPEED_LIMIT]
                    [--absolute_cost_speed ABSOLUTE_COST_SPEED]
train_cpo.py: error: unrecognized arguments: --normalize_obs=True
wandb: Waiting for W&B process to finish... (failed 2). Press Control-C to abort syncing.
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
2023-08-19 00:38:34,908 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 00:38:34,908 - wandb.wandb_agent - INFO - Agent starting run with config:
	lr: 0.001
	normalize_obs: True
2023-08-19 00:38:34,911 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo.py --lr=0.001 --normalize_obs=True
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
2023-08-19 07:38:35,150 - wandb.wandb_agent - INFO - Running runs: ['4jqpel8a']
2023-08-19 07:38:35,353 - wandb.wandb_agent - INFO - Running runs: ['iq2wvhp5']
2023-08-19 00:38:35,466 - wandb.wandb_agent - INFO - Running runs: ['4tc58zz4']
2023-08-19 00:38:35,746 - wandb.wandb_agent - INFO - Running runs: ['55vlrblr']
2023-08-19 00:38:35,806 - wandb.wandb_agent - INFO - Running runs: ['9qe4e2cu']
wandb: - 0.027 MB of 0.027 MB uploaded (0.000 MB deduped)wandb: \ 0.027 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: üöÄ View run glad-sweep-4 at: https://wandb.ai/ecrl/fast-safe-rl/runs/4jqpel8a
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_073833-4jqpel8a/logs
wandb: - 0.027 MB of 0.027 MB uploaded (0.000 MB deduped)wandb: \ 0.027 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: üöÄ View run glamorous-sweep-5 at: https://wandb.ai/ecrl/fast-safe-rl/runs/4tc58zz4
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_003833-4tc58zz4/logs
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: - 0.027 MB of 0.027 MB uploaded (0.000 MB deduped)wandb: \ 0.027 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: üöÄ View run kind-sweep-6 at: https://wandb.ai/ecrl/fast-safe-rl/runs/55vlrblr
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_003833-55vlrblr/logs
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: - 0.027 MB of 0.027 MB uploaded (0.000 MB deduped)wandb: \ 0.027 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: | 0.030 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: üöÄ View run fast-sweep-4 at: https://wandb.ai/ecrl/fast-safe-rl/runs/iq2wvhp5
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_073832-iq2wvhp5/logs
wandb: - 0.027 MB of 0.027 MB uploaded (0.000 MB deduped)wandb: \ 0.027 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: | 0.028 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: üöÄ View run daily-sweep-5 at: https://wandb.ai/ecrl/fast-safe-rl/runs/9qe4e2cu
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_003833-9qe4e2cu/logs
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_003837-vol60pie
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run usual-sweep-6
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/eito20j2
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/vol60pie
2023-08-19 00:38:39,920 - wandb.wandb_agent - INFO - Running runs: ['vol60pie']
usage: train_cpo.py [-h] [--task TASK] [--epoch EPOCH] [--target_kl TARGET_KL]
                    [--lr LR] [--step_per_epoch STEP_PER_EPOCH]
                    [--gamma GAMMA] [--cost_limit FLOAT [FLOAT ...]]
                    [--render RENDER] [--render_mode RENDER_MODE]
                    [--thread THREAD]
                    [--constraint_type CONSTRAINT_TYPE [CONSTRAINT_TYPE ...]]
                    [--speed_limit SPEED_LIMIT]
                    [--absolute_cost_speed ABSOLUTE_COST_SPEED]
train_cpo.py: error: unrecognized arguments: --normalize_obs=True
wandb: Waiting for W&B process to finish... (failed 2). Press Control-C to abort syncing.
2023-08-19 07:38:40,228 - wandb.wandb_agent - INFO - Cleaning up finished run: 4jqpel8a
2023-08-19 07:38:40,425 - wandb.wandb_agent - INFO - Cleaning up finished run: iq2wvhp5
2023-08-19 07:38:40,723 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 07:38:40,723 - wandb.wandb_agent - INFO - Agent starting run with config:
	actor_lr: 0.001
	critic_lr: 0.0005
	normalize_obs: False
2023-08-19 07:38:40,725 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py --actor_lr=0.001 --critic_lr=0.0005 --normalize_obs=False
2023-08-19 00:38:40,888 - wandb.wandb_agent - INFO - Cleaning up finished run: 9qe4e2cu
2023-08-19 07:38:40,903 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 07:38:40,903 - wandb.wandb_agent - INFO - Agent starting run with config:
	lr: 0.001
	normalize_obs: True
2023-08-19 07:38:40,904 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo.py --lr=0.001 --normalize_obs=True
2023-08-19 00:38:41,341 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 00:38:41,341 - wandb.wandb_agent - INFO - Agent starting run with config:
	lr: 0.0005
	normalize_obs: True
2023-08-19 00:38:41,345 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo.py --lr=0.0005 --normalize_obs=True
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: - 0.027 MB of 0.027 MB uploaded (0.000 MB deduped)wandb: \ 0.027 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: üöÄ View run usual-sweep-6 at: https://wandb.ai/ecrl/fast-safe-rl/runs/vol60pie
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_003837-vol60pie/logs
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_073843-pxsi2g4d
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run cosmic-sweep-7
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/eito20j2
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/pxsi2g4d
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_073843-ra77y1rn
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run scarlet-sweep-7
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/fjyc7cnz
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/ra77y1rn
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_003843-ptu1hjk7
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run wandering-sweep-8
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/eito20j2
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/ptu1hjk7
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
usage: train_cpo.py [-h] [--task TASK] [--epoch EPOCH] [--target_kl TARGET_KL]
                    [--lr LR] [--step_per_epoch STEP_PER_EPOCH]
                    [--gamma GAMMA] [--cost_limit FLOAT [FLOAT ...]]
                    [--render RENDER] [--render_mode RENDER_MODE]
                    [--thread THREAD]
                    [--constraint_type CONSTRAINT_TYPE [CONSTRAINT_TYPE ...]]
                    [--speed_limit SPEED_LIMIT]
                    [--absolute_cost_speed ABSOLUTE_COST_SPEED]
train_cpo.py: error: unrecognized arguments: --normalize_obs=True
wandb: Waiting for W&B process to finish... (failed 2). Press Control-C to abort syncing.
usage: train_cpo.py [-h] [--task TASK] [--epoch EPOCH] [--target_kl TARGET_KL]
                    [--lr LR] [--step_per_epoch STEP_PER_EPOCH]
                    [--gamma GAMMA] [--cost_limit FLOAT [FLOAT ...]]
                    [--render RENDER] [--render_mode RENDER_MODE]
                    [--thread THREAD]
                    [--constraint_type CONSTRAINT_TYPE [CONSTRAINT_TYPE ...]]
                    [--speed_limit SPEED_LIMIT]
                    [--absolute_cost_speed ABSOLUTE_COST_SPEED]
train_cpo.py: error: unrecognized arguments: --normalize_obs=True
wandb: Waiting for W&B process to finish... (failed 2). Press Control-C to abort syncing.
2023-08-19 00:38:45,609 - wandb.wandb_agent - INFO - Cleaning up finished run: 4tc58zz4
2023-08-19 07:38:45,734 - wandb.wandb_agent - INFO - Running runs: ['ra77y1rn']
2023-08-19 00:38:45,891 - wandb.wandb_agent - INFO - Cleaning up finished run: 55vlrblr
2023-08-19 07:38:45,913 - wandb.wandb_agent - INFO - Running runs: ['pxsi2g4d']
2023-08-19 00:38:46,078 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 00:38:46,078 - wandb.wandb_agent - INFO - Agent starting run with config:
	actor_lr: 0.001
	critic_lr: 0.0005
	normalize_obs: True
2023-08-19 00:38:46,080 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py --actor_lr=0.001 --critic_lr=0.0005 --normalize_obs=True
2023-08-19 00:38:46,308 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 00:38:46,309 - wandb.wandb_agent - INFO - Agent starting run with config:
	actor_lr: 0.001
	critic_lr: 0.0005
	normalize_obs: False
2023-08-19 00:38:46,312 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py --actor_lr=0.001 --critic_lr=0.0005 --normalize_obs=False
2023-08-19 00:38:46,355 - wandb.wandb_agent - INFO - Running runs: ['ptu1hjk7']
wandb: - 0.027 MB of 0.027 MB uploaded (0.000 MB deduped)wandb: \ 0.027 MB of 0.032 MB uploaded (0.000 MB deduped)wandb: üöÄ View run scarlet-sweep-7 at: https://wandb.ai/ecrl/fast-safe-rl/runs/ra77y1rn
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_073843-ra77y1rn/logs
wandb: - 0.027 MB of 0.027 MB uploaded (0.000 MB deduped)wandb: \ 0.027 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: | 0.028 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: üöÄ View run cosmic-sweep-7 at: https://wandb.ai/ecrl/fast-safe-rl/runs/pxsi2g4d
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_073843-pxsi2g4d/logs
wandb: üöÄ View run wandering-sweep-8 at: https://wandb.ai/ecrl/fast-safe-rl/runs/ptu1hjk7
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_003843-ptu1hjk7/logs
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
2023-08-19 00:38:50,059 - wandb.wandb_agent - INFO - Cleaning up finished run: vol60pie
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_003849-mvso41ag
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run good-sweep-9
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/fjyc7cnz
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/mvso41ag
2023-08-19 00:38:50,420 - wandb.wandb_agent - INFO - Agent received command: run
2023-08-19 00:38:50,420 - wandb.wandb_agent - INFO - Agent starting run with config:
	lr: 0.001
	normalize_obs: False
2023-08-19 00:38:50,423 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo.py --lr=0.001 --normalize_obs=False
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_003849-fhvc6upa
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run robust-sweep-8
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/fjyc7cnz
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/fhvc6upa
2023-08-19 07:38:50,812 - wandb.wandb_agent - ERROR - Detected 3 failed runs in the first 60 seconds, shutting down.
2023-08-19 07:38:50,812 - wandb.wandb_agent - INFO - To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
wandb: Terminating and syncing runs. Press ctrl-c to kill.
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
2023-08-19 07:38:50,989 - wandb.wandb_agent - ERROR - Detected 3 failed runs in the first 60 seconds, shutting down.
2023-08-19 07:38:50,989 - wandb.wandb_agent - INFO - To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
wandb: Terminating and syncing runs. Press ctrl-c to kill.
2023-08-19 00:38:51,089 - wandb.wandb_agent - INFO - Running runs: ['fhvc6upa']
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 163, in __getattr__
    return self.__getitem__(key)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 75, in <module>
    class MyCfg(TrainCfg):
  File "/nas/ucb/mason/ethically-compliant-rl/CVPO/train_cvpo.py", line 76, in MyCfg
    task: str = args.task
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'task'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
2023-08-19 00:38:51,322 - wandb.wandb_agent - INFO - Running runs: ['mvso41ag']
2023-08-19 00:38:51,431 - wandb.wandb_agent - ERROR - Detected 3 failed runs in the first 60 seconds, shutting down.
2023-08-19 00:38:51,431 - wandb.wandb_agent - INFO - To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
wandb: Terminating and syncing runs. Press ctrl-c to kill.
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/mason/.netrc
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230819_003853-snz70x67
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run brisk-sweep-9
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üßπ View sweep at https://wandb.ai/ecrl/fast-safe-rl/sweeps/eito20j2
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/snz70x67
wandb: - 0.027 MB of 0.027 MB uploaded (0.000 MB deduped)wandb: \ 0.027 MB of 0.029 MB uploaded (0.000 MB deduped)wandb: üöÄ View run good-sweep-9 at: https://wandb.ai/ecrl/fast-safe-rl/runs/mvso41ag
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_003849-mvso41ag/logs
wandb: üöÄ View run robust-sweep-8 at: https://wandb.ai/ecrl/fast-safe-rl/runs/fhvc6upa
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_003849-fhvc6upa/logs
usage: train_cpo.py [-h] [--task TASK] [--epoch EPOCH] [--target_kl TARGET_KL]
                    [--lr LR] [--step_per_epoch STEP_PER_EPOCH]
                    [--gamma GAMMA] [--cost_limit FLOAT [FLOAT ...]]
                    [--render RENDER] [--render_mode RENDER_MODE]
                    [--thread THREAD]
                    [--constraint_type CONSTRAINT_TYPE [CONSTRAINT_TYPE ...]]
                    [--speed_limit SPEED_LIMIT]
                    [--absolute_cost_speed ABSOLUTE_COST_SPEED]
train_cpo.py: error: unrecognized arguments: --normalize_obs=False
wandb: Waiting for W&B process to finish... (failed 2). Press Control-C to abort syncing.
2023-08-19 00:38:55,434 - wandb.wandb_agent - INFO - Running runs: ['snz70x67']
2023-08-19 00:38:56,393 - wandb.wandb_agent - ERROR - Detected 3 failed runs in the first 60 seconds, shutting down.
2023-08-19 00:38:56,394 - wandb.wandb_agent - INFO - To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
wandb: Terminating and syncing runs. Press ctrl-c to kill.
wandb: - 0.027 MB of 0.027 MB uploaded (0.000 MB deduped)wandb: \ 0.027 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: | 0.030 MB of 0.030 MB uploaded (0.000 MB deduped)wandb: üöÄ View run brisk-sweep-9 at: https://wandb.ai/ecrl/fast-safe-rl/runs/snz70x67
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230819_003853-snz70x67/logs
2023-08-19 00:39:01,239 - wandb.wandb_agent - ERROR - Detected 3 failed runs in the first 60 seconds, shutting down.
2023-08-19 00:39:01,239 - wandb.wandb_agent - INFO - To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
wandb: Terminating and syncing runs. Press ctrl-c to kill.
2023-08-19 00:39:05,566 - wandb.wandb_agent - ERROR - Detected 3 failed runs in the first 60 seconds, shutting down.
2023-08-19 00:39:05,566 - wandb.wandb_agent - INFO - To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
wandb: Terminating and syncing runs. Press ctrl-c to kill.
