wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: wandb version 0.15.7 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20230727_162749-cf59f9db-0164-4a82-b0ac-067691cb64bf
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run cpo_lr0.01-61ce
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/fast-safe-rl
wandb: üöÄ View run at https://wandb.ai/ecrl/fast-safe-rl/runs/cf59f9db-0164-4a82-b0ac-067691cb64bf
2023-07-27 16:28:02,509	INFO worker.py:1621 -- Started a local Ray instance.
[32;1mLogging data to logs/fast-safe-rl/parking-v0-cost-10/cpo_lr0.01-61ce/progress.txt[0m
[36;1mSaving config:
[0m
{
    "action_bound_method":	"clip",
    "action_scaling":	true,
    "backtrack_coeff":	0.8,
    "batch_size":	99999,
    "buffer_size":	100000,
    "cost_limit":	10,
    "damping_coeff":	0.1,
    "deterministic_eval":	true,
    "device":	"cpu",
    "env_config_file":	"configs/ParkingEnv/env-image.txt",
    "episode_per_collect":	20,
    "epoch":	40,
    "gae_lambda":	0.95,
    "gamma":	0.99,
    "group":	null,
    "hidden_sizes":	[
        128,
        128
    ],
    "l2_reg":	0.001,
    "last_layer_scale":	false,
    "logdir":	"logs",
    "lr":	0.01,
    "max_backtracks":	100,
    "max_batchsize":	99999,
    "name":	"cpo_lr0.01-61ce",
    "norm_adv":	true,
    "optim_critic_iters":	10,
    "prefix":	"cpo",
    "project":	"fast-safe-rl",
    "render":	null,
    "render_mode":	null,
    "repeat_per_collect":	4,
    "resume":	false,
    "rew_norm":	false,
    "reward_threshold":	10000,
    "save_ckpt":	true,
    "save_interval":	4,
    "seed":	10,
    "step_per_epoch":	10000,
    "suffix":	"",
    "target_kl":	0.01,
    "task":	"parking-v0",
    "testing_num":	2,
    "thread":	320,
    "training_num":	20,
    "unbounded":	false,
    "use_default_cfg":	false,
    "verbose":	true,
    "worker":	"RayVectorEnv"
}
Observation Space: Box(0, 255, (4, 128, 128), uint8)
Action Space: Box(-1.0, 1.0, (2,), float32)
Render Mode: None
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 687, in ray._raylet.prepare_args_internal
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/_private/serialization.py", line 468, in serialize
    return self._serialize_to_msgpack(value)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/_private/serialization.py", line 446, in _serialize_to_msgpack
    pickle5_serialized_object = self._serialize_to_pickle5(
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/_private/serialization.py", line 408, in _serialize_to_pickle5
    raise e
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/_private/serialization.py", line 403, in _serialize_to_pickle5
    inband = pickle.dumps(
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps
    cp.dump(obj)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'WorldSurface' object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo.py", line 212, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo.py", line 174, in train
    train_envs = worker([lambda: load_environment(ENV_CONFIG) for _ in range(training_num)])
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/tianshou/env/venvs.py", line 499, in __init__
    super().__init__(env_fns, RayEnvWorker, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/tianshou/env/venvs.py", line 153, in __init__
    self.workers = [worker_fn(_patch_env_generator(fn)) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/tianshou/env/venvs.py", line 153, in <listcomp>
    self.workers = [worker_fn(_patch_env_generator(fn)) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/tianshou/env/worker/ray.py", line 28, in __init__
    self.env = ray.remote(_SetAttrWrapper).options(  # type: ignore
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/actor.py", line 645, in remote
    return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 385, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/actor.py", line 970, in _remote
    actor_id = worker.core_worker.create_actor(
  File "python/ray/_raylet.pyx", line 3206, in ray._raylet.CoreWorker.create_actor
  File "python/ray/_raylet.pyx", line 3211, in ray._raylet.CoreWorker.create_actor
  File "python/ray/_raylet.pyx", line 649, in ray._raylet.prepare_args_and_increment_put_refs
  File "python/ray/_raylet.pyx", line 640, in ray._raylet.prepare_args_and_increment_put_refs
  File "python/ray/_raylet.pyx", line 696, in ray._raylet.prepare_args_internal
TypeError: Could not serialize the argument <OrderEnforcing<PassiveEnvChecker<ParkingEnv<parking-v0>>>> for a task or actor tianshou.env.worker.ray._SetAttrWrapper.__init__:
================================================================================
Checking Serializability of <OrderEnforcing<PassiveEnvChecker<ParkingEnv<parking-v0>>>>
================================================================================
!!! FAIL serialization: cannot pickle 'WorldSurface' object
    Serializing '_action_space' None...
    Serializing '_cached_spec' EnvSpec(id='parking-v0', entry_point='highway_env.envs:ParkingEnv', reward_threshold=None, nondeterministic=False, max_episode_steps=None, order_enforce=True, autoreset=False, disable_env_checker=False, apply_api_compatibility=False, kwargs={'render_mode': None}, namespace=None, name='parking', version=0, additional_wrappers=(), vector_entry_point=None)...
    Serializing '_disable_render_order_enforcing' False...
    Serializing '_has_reset' True...
    Serializing '_is_protocol' False...
    Serializing '_metadata' None...
    Serializing '_observation_space' None...
    Serializing '_reward_range' None...
    Serializing '_saved_kwargs' {'disable_render_order_enforcing': False}...
    Serializing 'action_space' Box(-1.0, 1.0, (2,), float32)...
    Serializing 'class_name' <bound method Wrapper.class_name of <class 'gymnasium.wrappers.order_enforcing.OrderEnforcing'>>...
    Serializing 'close' <bound method Wrapper.close of <OrderEnforcing<PassiveEnvChecker<ParkingEnv<parking-v0>>>>>...
    !!! FAIL serialization: cannot pickle 'WorldSurface' object
        Serializing '__func__' <function Wrapper.close at 0x14feef7da820>...
    WARNING: Did not find non-serializable object in <bound method Wrapper.close of <OrderEnforcing<PassiveEnvChecker<ParkingEnv<parking-v0>>>>>. This may be an oversight.
================================================================================
Variable: 

	FailTuple(close [obj=<bound method Wrapper.close of <OrderEnforcing<PassiveEnvChecker<ParkingEnv<parking-v0>>>>>, parent=<OrderEnforcing<PassiveEnvChecker<ParkingEnv<parking-v0>>>>])

was found to be non-serializable. There may be multiple other undetected variables that were non-serializable. 
Consider either removing the instantiation/imports of these variables or moving the instantiation into the scope of the function/class. 
================================================================================
Check https://docs.ray.io/en/master/ray-core/objects/serialization.html#troubleshooting for more information.
If you have any suggestions on how to improve this error message, please reach out to the Ray developers on github.com/ray-project/ray/issues/
================================================================================

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 687, in ray._raylet.prepare_args_internal
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/_private/serialization.py", line 468, in serialize
    return self._serialize_to_msgpack(value)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/_private/serialization.py", line 446, in _serialize_to_msgpack
    pickle5_serialized_object = self._serialize_to_pickle5(
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/_private/serialization.py", line 408, in _serialize_to_pickle5
    raise e
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/_private/serialization.py", line 403, in _serialize_to_pickle5
    inband = pickle.dumps(
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps
    cp.dump(obj)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'WorldSurface' object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo.py", line 212, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo.py", line 174, in train
    train_envs = worker([lambda: load_environment(ENV_CONFIG) for _ in range(training_num)])
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/tianshou/env/venvs.py", line 499, in __init__
    super().__init__(env_fns, RayEnvWorker, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/tianshou/env/venvs.py", line 153, in __init__
    self.workers = [worker_fn(_patch_env_generator(fn)) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/tianshou/env/venvs.py", line 153, in <listcomp>
    self.workers = [worker_fn(_patch_env_generator(fn)) for fn in env_fns]
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/tianshou/env/worker/ray.py", line 28, in __init__
    self.env = ray.remote(_SetAttrWrapper).options(  # type: ignore
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/actor.py", line 645, in remote
    return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 385, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/ray/actor.py", line 970, in _remote
    actor_id = worker.core_worker.create_actor(
  File "python/ray/_raylet.pyx", line 3206, in ray._raylet.CoreWorker.create_actor
  File "python/ray/_raylet.pyx", line 3211, in ray._raylet.CoreWorker.create_actor
  File "python/ray/_raylet.pyx", line 649, in ray._raylet.prepare_args_and_increment_put_refs
  File "python/ray/_raylet.pyx", line 640, in ray._raylet.prepare_args_and_increment_put_refs
  File "python/ray/_raylet.pyx", line 696, in ray._raylet.prepare_args_internal
TypeError: Could not serialize the argument <OrderEnforcing<PassiveEnvChecker<ParkingEnv<parking-v0>>>> for a task or actor tianshou.env.worker.ray._SetAttrWrapper.__init__:
================================================================================
Checking Serializability of <OrderEnforcing<PassiveEnvChecker<ParkingEnv<parking-v0>>>>
================================================================================
!!! FAIL serialization: cannot pickle 'WorldSurface' object
    Serializing '_action_space' None...
    Serializing '_cached_spec' EnvSpec(id='parking-v0', entry_point='highway_env.envs:ParkingEnv', reward_threshold=None, nondeterministic=False, max_episode_steps=None, order_enforce=True, autoreset=False, disable_env_checker=False, apply_api_compatibility=False, kwargs={'render_mode': None}, namespace=None, name='parking', version=0, additional_wrappers=(), vector_entry_point=None)...
    Serializing '_disable_render_order_enforcing' False...
    Serializing '_has_reset' True...
    Serializing '_is_protocol' False...
    Serializing '_metadata' None...
    Serializing '_observation_space' None...
    Serializing '_reward_range' None...
    Serializing '_saved_kwargs' {'disable_render_order_enforcing': False}...
    Serializing 'action_space' Box(-1.0, 1.0, (2,), float32)...
    Serializing 'class_name' <bound method Wrapper.class_name of <class 'gymnasium.wrappers.order_enforcing.OrderEnforcing'>>...
    Serializing 'close' <bound method Wrapper.close of <OrderEnforcing<PassiveEnvChecker<ParkingEnv<parking-v0>>>>>...
    !!! FAIL serialization: cannot pickle 'WorldSurface' object
        Serializing '__func__' <function Wrapper.close at 0x14feef7da820>...
    WARNING: Did not find non-serializable object in <bound method Wrapper.close of <OrderEnforcing<PassiveEnvChecker<ParkingEnv<parking-v0>>>>>. This may be an oversight.
================================================================================
Variable: 

	FailTuple(close [obj=<bound method Wrapper.close of <OrderEnforcing<PassiveEnvChecker<ParkingEnv<parking-v0>>>>>, parent=<OrderEnforcing<PassiveEnvChecker<ParkingEnv<parking-v0>>>>])

was found to be non-serializable. There may be multiple other undetected variables that were non-serializable. 
Consider either removing the instantiation/imports of these variables or moving the instantiation into the scope of the function/class. 
================================================================================
Check https://docs.ray.io/en/master/ray-core/objects/serialization.html#troubleshooting for more information.
If you have any suggestions on how to improve this error message, please reach out to the Ray developers on github.com/ray-project/ray/issues/
================================================================================

wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: üöÄ View run cpo_lr0.01-61ce at: https://wandb.ai/ecrl/fast-safe-rl/runs/cf59f9db-0164-4a82-b0ac-067691cb64bf
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230727_162749-cf59f9db-0164-4a82-b0ac-067691cb64bf/logs
srun: error: gan.ist.berkeley.edu: task 0: Exited with exit code 1
